export const PROFILE_CONSTANTS = {
  DEFAULT_AMOUNT: [100000],
  AVATAR_SIZE: {
    MOBILE: "w-20 h-20",
    DESKTOP: "w-28 h-28",
  },
  HEADER_HEIGHT: {
    MOBILE: "h-32",
    SM: "h-40",
    LG: "h-56",
  },
} as const;

export const PROFILE_TABS: Array<{ id: string; label: string }> = [
  { id: "details", label: "My details" },
  { id: "beneficiary", label: "Beneficiary Details" },
  { id: "financial", label: "Financial details" },
] as const;

export const TITLE_OPTIONS: Array<{ id: string; label: string }> = [
  { id: "mr", label: "Mr" },
  { id: "mrs", label: "Mrs" },
  { id: "ms", label: "Ms" },
  { id: "dr", label: "Dr" },
  { id: "prof", label: "Prof" },
] as const;

export const GENDER_OPTIONS: Array<{ id: string; label: string }> = [
  { id: "male", label: "Male" },
  { id: "female", label: "Female" },
  { id: "other", label: "Other" },
  { id: "prefer-not-to-say", label: "Prefer not to say" },
] as const;

export const NATIONALITY_OPTIONS: Array<{ id: string; label: string }> = [
  { id: "afghan", label: "Afghan" },
  { id: "albanian", label: "Albanian" },
  { id: "algerian", label: "Algerian" },
  { id: "american-samoan", label: "American Samoan" },
  { id: "andorran", label: "Andorran" },
  { id: "angolan", label: "Angolan" },
  { id: "anguillan", label: "Anguillan" },
  { id: "antarctican", label: "Antarctican" },
  { id: "antiguan-or-barbudan", label: "Antiguan or Barbudan" },
  { id: "argentine", label: "Argentine" },
  { id: "armenian", label: "Armenian" },
  { id: "aruban", label: "Aruban" },
  { id: "australian", label: "Australian" },
  { id: "austrian", label: "Austrian" },
  { id: "azerbaijani", label: "Azerbaijani" },
  { id: "bahamian", label: "Bahamian" },
  { id: "bahraini", label: "Bahraini" },
  { id: "bangladeshi", label: "Bangladeshi" },
  { id: "barbadian", label: "Barbadian" },
  { id: "belarusian", label: "Belarusian" },
  { id: "belgian", label: "Belgian" },
  { id: "belizean", label: "Belizean" },
  { id: "beninese", label: "Beninese" },
  { id: "bermudian", label: "Bermudian" },
  { id: "bhutanese", label: "Bhutanese" },
  { id: "bolivian", label: "Bolivian" },
  { id: "bosnian-or-herzegovinian", label: "Bosnian or Herzegovinian" },
  { id: "botswanan", label: "Botswanan" },
  { id: "bouvet-islander", label: "Bouvet Islander" },
  { id: "brazilian", label: "Brazilian" },
  {
    id: "british-indian-ocean-territory",
    label: "British Indian Ocean Territory",
  },
  { id: "british-virgin-islander", label: "British Virgin Islander" },
  { id: "bruneian", label: "Bruneian" },
  { id: "bulgarian", label: "Bulgarian" },
  { id: "burkinabe", label: "Burkinabé" },
  { id: "burundian", label: "Burundian" },
  { id: "cambodian", label: "Cambodian" },
  { id: "cameroonian", label: "Cameroonian" },
  { id: "canadian", label: "Canadian" },
  { id: "cape-verdean", label: "Cape Verdean" },
  { id: "caribbean-netherlands", label: "Caribbean Netherlands" },
  { id: "cayman-islander", label: "Cayman Islander" },
  { id: "central-african", label: "Central African" },
  { id: "chadian", label: "Chadian" },
  { id: "chilean", label: "Chilean" },
  { id: "chinese", label: "Chinese" },
  { id: "christmas-islander", label: "Christmas Islander" },
  { id: "cocos-islander", label: "Cocos Islander" },
  { id: "colombian", label: "Colombian" },
  { id: "comoran", label: "Comoran" },
  { id: "congolese-brazzaville", label: "Congolese (Brazzaville)" },
  { id: "congolese-kinshasa", label: "Congolese (Kinshasa)" },
  { id: "cook-islander", label: "Cook Islander" },
  { id: "costa-rican", label: "Costa Rican" },
  { id: "croatian", label: "Croatian" },
  { id: "cuban", label: "Cuban" },
  { id: "curacaoan", label: "Curaçaoan" },
  { id: "cypriot", label: "Cypriot" },
  { id: "czech", label: "Czech" },
  { id: "ivoirian", label: "Ivoirian" },
  { id: "danish", label: "Danish" },
  { id: "djiboutian", label: "Djiboutian" },
  { id: "dominican", label: "Dominican" },
  { id: "dominican-republic", label: "Dominican (Republic)" },
  { id: "ecuadorean", label: "Ecuadorean" },
  { id: "egyptian", label: "Egyptian" },
  { id: "salvadoran", label: "Salvadoran" },
  { id: "equatorial-guinean", label: "Equatorial Guinean" },
  { id: "eritrean", label: "Eritrean" },
  { id: "estonian", label: "Estonian" },
  { id: "eswatini", label: "Eswatini" },
  { id: "ethiopian", label: "Ethiopian" },
  { id: "falkland-islander", label: "Falkland Islander" },
  { id: "faroese", label: "Faroese" },
  { id: "fijian", label: "Fijian" },
  { id: "finnish", label: "Finnish" },
  { id: "french", label: "French" },
  { id: "french-guianese", label: "French Guianese" },
  { id: "french-polynesian", label: "French Polynesian" },
  { id: "french-southern-territories", label: "French Southern Territories" },
  { id: "gabonese", label: "Gabonese" },
  { id: "gambian", label: "Gambian" },
  { id: "georgian", label: "Georgian" },
  { id: "german", label: "German" },
  { id: "ghanaian", label: "Ghanaian" },
  { id: "gibraltarian", label: "Gibraltarian" },
  { id: "greek", label: "Greek" },
  { id: "greenlander", label: "Greenlander" },
  { id: "grenadian", label: "Grenadian" },
  { id: "guadeloupean", label: "Guadeloupean" },
  { id: "guamanian", label: "Guamanian" },
  { id: "guatemalan", label: "Guatemalan" },
  { id: "guernsey", label: "Guernsey" },
  { id: "guinean", label: "Guinean" },
  { id: "guinea-bissauan", label: "Guinea-Bissauan" },
  { id: "guyanese", label: "Guyanese" },
  { id: "haitian", label: "Haitian" },
  { id: "heard-islander", label: "Heard Islander" },
  { id: "honduran", label: "Honduran" },
];

export const COUNTRY_OPTIONS: Array<{ id: string; label: string }> = [
  { id: "afghanistan", label: "Afghanistan" },
  { id: "albania", label: "Albania" },
  { id: "algeria", label: "Algeria" },
  { id: "american-samoa", label: "American Samoa" },
  { id: "andorra", label: "Andorra" },
  { id: "angola", label: "Angola" },
  { id: "anguilla", label: "Anguilla" },
  { id: "antarctica", label: "Antarctica" },
  { id: "antigua-and-barbuda", label: "Antigua & Barbuda" },
  { id: "argentina", label: "Argentina" },
  { id: "armenia", label: "Armenia" },
  { id: "aruba", label: "Aruba" },
  { id: "australia", label: "Australia" },
  { id: "austria", label: "Austria" },
  { id: "azerbaijan", label: "Azerbaijan" },
  { id: "bahamas", label: "Bahamas" },
  { id: "bahrain", label: "Bahrain" },
  { id: "bangladesh", label: "Bangladesh" },
  { id: "barbados", label: "Barbados" },
  { id: "belarus", label: "Belarus" },
  { id: "belgium", label: "Belgium" },
  { id: "belize", label: "Belize" },
  { id: "benin", label: "Benin" },
  { id: "bermuda", label: "Bermuda" },
  { id: "bhutan", label: "Bhutan" },
  { id: "bolivia", label: "Bolivia" },
  { id: "bosnia-and-herzegovina", label: "Bosnia & Herzegovina" },
  { id: "botswana", label: "Botswana" },
  { id: "bouvet-island", label: "Bouvet Island" },
  { id: "brazil", label: "Brazil" },
  {
    id: "british-indian-ocean-territory",
    label: "British Indian Ocean Territory",
  },
  { id: "british-virgin-islands", label: "British Virgin Islands" },
  { id: "brunei", label: "Brunei" },
  { id: "bulgaria", label: "Bulgaria" },
  { id: "burkina-faso", label: "Burkina Faso" },
  { id: "burundi", label: "Burundi" },
  { id: "cambodia", label: "Cambodia" },
  { id: "cameroon", label: "Cameroon" },
  { id: "canada", label: "Canada" },
  { id: "cape-verde", label: "Cape Verde" },
  { id: "caribbean-netherlands", label: "Caribbean Netherlands" },
  { id: "cayman-islands", label: "Cayman Islands" },
  { id: "central-african-republic", label: "Central African Republic" },
  { id: "chad", label: "Chad" },
  { id: "chile", label: "Chile" },
  { id: "china", label: "China" },
  { id: "christmas-island", label: "Christmas Island" },
  { id: "cocos-keeling-islands", label: "Cocos (Keeling) Islands" },
  { id: "colombia", label: "Colombia" },
  { id: "comoros", label: "Comoros" },
  { id: "congo-brazzaville", label: "Congo - Brazzaville" },
  { id: "congo-kinshasa", label: "Congo - Kinshasa" },
  { id: "cook-islands", label: "Cook Islands" },
  { id: "costa-rica", label: "Costa Rica" },
  { id: "croatia", label: "Croatia" },
  { id: "cuba", label: "Cuba" },
  { id: "curacao", label: "Curaçao" },
  { id: "cyprus", label: "Cyprus" },
  { id: "czechia", label: "Czechia" },
  { id: "cote-divoire", label: "Côte d’Ivoire" },
  { id: "denmark", label: "Denmark" },
  { id: "djibouti", label: "Djibouti" },
  { id: "dominica", label: "Dominica" },
  { id: "dominican-republic", label: "Dominican Republic" },
  { id: "ecuador", label: "Ecuador" },
  { id: "egypt", label: "Egypt" },
  { id: "el-salvador", label: "El Salvador" },
  { id: "equatorial-guinea", label: "Equatorial Guinea" },
  { id: "eritrea", label: "Eritrea" },
  { id: "estonia", label: "Estonia" },
  { id: "eswatini", label: "Eswatini" },
  { id: "ethiopia", label: "Ethiopia" },
  { id: "falkland-islands", label: "Falkland Islands" },
  { id: "faroe-islands", label: "Faroe Islands" },
  { id: "fiji", label: "Fiji" },
  { id: "finland", label: "Finland" },
  { id: "france", label: "France" },
  { id: "french-guiana", label: "French Guiana" },
  { id: "french-polynesia", label: "French Polynesia" },
  { id: "french-southern-territories", label: "French Southern Territories" },
  { id: "gabon", label: "Gabon" },
  { id: "gambia", label: "Gambia" },
  { id: "georgia", label: "Georgia" },
  { id: "germany", label: "Germany" },
  { id: "ghana", label: "Ghana" },
  { id: "gibraltar", label: "Gibraltar" },
  { id: "greece", label: "Greece" },
  { id: "greenland", label: "Greenland" },
  { id: "grenada", label: "Grenada" },
  { id: "guadeloupe", label: "Guadeloupe" },
  { id: "guam", label: "Guam" },
  { id: "guatemala", label: "Guatemala" },
  { id: "guernsey", label: "Guernsey" },
  { id: "guinea", label: "Guinea" },
  { id: "guinea-bissau", label: "Guinea-Bissau" },
  { id: "guyana", label: "Guyana" },
  { id: "haiti", label: "Haiti" },
  { id: "heard-and-mcdonald-islands", label: "Heard & McDonald Islands" },
  { id: "honduras", label: "Honduras" },
] as const;


export const RACE_OPTIONS: Array<{ id: string; label: string }> = [
  { id: "african", label: "Black African" },
  { id: "coloured", label: "Coloured" },
  { id: "caucasian", label: "Caucasian" },
  { id: "indian", label: "Indian" },
  { id: "asian", label: "asian" },
  { id: "white", label: "White" },
  { id: "other", label: "Other" },
] as const;

export const COMMUNICATION_OPTIONS: Array<{ id: string; label: string }> = [
  { id: "email", label: "Email" },
  { id: "sms", label: "SMS" },
  { id: "whatsapp", label: "WhatsApp" },
  { id: "phone", label: "Phone call" },
] as const;

export const EMPLOYMENT_STATUS_OPTIONS: Array<{ id: string; label: string }> = [
  { id: "employed", label: "Employed (Full-time)" },
  { id: "self-employed", label: "Employed (Part-time)" },
  { id: "unemployed", label: "Unemployed" },
  { id: "student", label: "Student" },
  { id: "retired", label: "Retired" },
  { id: "other", label: "Other" },
] as const;

export const DEPOSIT_FREQUENCY_OPTIONS: Array<{ id: string; label: string }> = [
  { id: "Ad hoc", label: "Ad hoc" },
  { id: "Lump Sum", label: "Lump Sum" },
  { id: "Monthly", label: "Monthly" },
  { id: "Quarterly", label: "Quarterly" },
] as const;

export const BANK_OPTIONS: Array<{ id: string; label: string }> = [
  { id: "ABSA", label: "ABSA" },
  { id: "fnb", label: "FNB" },
  { id: "standard-bank", label: "Standard Bank" },
  { id: "nedbank", label: "Nedbank" },
  { id: "capitec", label: "Capitec" },
  { id: "other", label: "Other" },
] as const;

export const BENEFICIARY_TYPE_OPTIONS: Array<{ id: string; label: string }> = [
  { id: "My Estate", label: "My Estate" },
  { id: "My Beneficiary", label: "My Beneficiary" },
] as const;

export const RELATION_OPTIONS: Array<{ id: string; label: string }> = [
  { id: "spouse", label: "Spouse" },
  { id: "child", label: "Child" },
  { id: "parent", label: "Parent" },
  { id: "sibling", label: "Sibling" },
  { id: "other", label: "Other" },
] as const;

export const SAVING_FOR_OPTIONS: Array<{ id: string; label: string }> = [
  { id: "Develop Savings Habit", label: "Develop Savings Habit" },
  { id: "Januworry blues", label: "Januworry blues" },
  { id: "Pay School Fees", label: "Pay School Fees" },
  { id: "Pay off Debt", label: "Pay off Debt" },
  { id: "Plan for the Year", label: "Plan for the Year Fund" },
  { id: "Other", label: "Other" },
] as const;

export const FUND_SOURCE_OPTIONS: Array<{ id: string; label: string }> = [
  { id: "Allowance", label: "Allowance" },
  { id: "Business Profit", label: "Business Profit" },
  { id: "Employment Income", label: "Employment Income" },
  { id: "Inheritance", label: "Inheritance" },
  { id: "Investments", label: "Investments" },
  { id: "Pension", label: "Pension" },
  { id: "Social Welfare Grant", label: "Social Welfare Grant" },
  { id: "Other", label: "Other" },
] as const;

export const PROFILE_MESSAGES = {
  LOADING: "Loading profile...",
  ERROR: "Failed to load profile",
  ERROR_DESCRIPTION: "Please try refreshing the page",
  SUCCESS_UPDATE: "Profile updated successfully",
  ERROR_UPDATE: "Failed to update profile",
} as const;
